export const INIT_SETTING_DATA = "INIT_SETTING_DATA";

export const INIT_CAMPAIGN_DATA = "INIT_CAMPAIGN_DATA";
export const CREATE_CAMPAIGN_DATA = "CREATE_CAMPAIGN_DATA";
export const UPDATE_CAMPAIGN_DATA = "UPDATE_CAMPAIGN_DATA";
export const DELETE_CAMPAIGN_DATA = "DELETE_CAMPAIGN_DATA";
export const UPDATE_CAMPAIGN_FIELD_DATA = "UPDATE_CAMPAIGN_FIELD_DATA";

export const INIT_GROUP_DATA = "INIT_GROUP_DATA";
export const CREATE_GROUP_DATA = "CREATE_GROUP_DATA";
export const UPDATE_GROUP_DATA = "UPDATE_GROUP_DATA";
export const UPDATE_GROUP_CAMPAIGN_OBJECT_DATA = "UPDATE_GROUP_CAMPAIGN_OBJECT_DATA";
export const UPDATE_GROUP_CAMPAIGN_FIELD_DATA = "UPDATE_GROUP_CAMPAIGN_FIELD_DATA";
export const DELETE_GROUP_DATA = "DELETE_GROUP_DATA";
export const UPDATE_IS_MANUALLY = "UPDATE_IS_MANUALLY";