export const INIT_SETTING_DATA = "INIT_SETTING_DATA";

export const INIT_CAMPAIGN_DATA = "INIT_CAMPAIGN_DATA";
export const INSERT_CAMPAIGN_DATA = "INSERT_CAMPAIGN_DATA";
export const UPDATE_CAMPAIGN_DATA = "UPDATE_CAMPAIGN_DATA";
export const DELETE_CAMPAIGN_DATA = "DELETE_CAMPAIGN_DATA";